project_id = "wxqkltocjmtxjbvxfxfc"

[functions.change-background]
verify_jwt = false

[functions.edit-photo]
verify_jwt = false

[functions.notify-new-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.designer-studio]
verify_jwt = false